export const roles = [
  "Actor",
  "Model",
  "Musical Artist",
  "Dancer",
  "Hostess",
  "Voice Over Artist",
  "Fashion Designer",
  "Presenter",
  "Influencer",
  "Script Writer",
  "Movie Producer",
  "Movie Director",
  "Graphics Designer",
  "Web Developer",
  "Digital Marketer",
  "Cinematographer",
  "Event Planner",
  "Driver",
];
